version: '2'

networks:
  nats-network: {}

services:
  nats1:
    networks: ["nats-network"]
    image: "nats:0.9.6"
    entrypoint: "/gnatsd --routes nats://nats2:6222,nats://nats3:6222 --cluster nats://0.0.0.0:6222"
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
  nats2:
    networks: ["nats-network"]
    image: "nats:0.9.6"
    entrypoint: "/gnatsd --routes nats://nats1:6222,nats://nats3:6222 --cluster nats://0.0.0.0:6222"
    ports:
      - "4223:4222"
      - "6223:6222"
      - "8223:8222"
  nats3:
    networks: ["nats-network"]
    image: "nats:0.9.6"
    entrypoint: "/gnatsd --routes nats://nats1:6222,nats://nats2:6222 --cluster nats://0.0.0.0:6222"
    ports:
      - "4224:4222"
      - "6224:6222"
      - "8224:8222"
